//  Login 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_START = 'LOGIN_START';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Signup

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGN_UP_START = 'SIGN_UP_START';

//  Error handler
 export const NETWORK_ERROR = 'NETWORK_ERROR';
 export const SERVER_ERROR = 'SERVER_ERROR';

//  Forgot password 
export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

// Add new school

export const ADD_SCHOOL_SUCCESS = 'ADD_SCHOOL_SUCCESS';
export const ADD_SCHOOL_FAILURE = 'ADD_SCHOOL_FAILURE';
export const ADD_SCHOOL_START = 'ADD_SCHOOL_START';

// Add new staff member

export const ADD_STAFF_START = 'ADD_STAFF_START';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_ERROR = 'ADD_STAFF_ERROR';

// Get all staffs
export const GET_STAFFS_START = 'GET_STAFFS_START';
export const GET_STAFFS_SUCCESS = 'GET_STAFFS_SUCCESS';
export const GET_STAFFS_ERROR = 'GET_STAFFS_ERROR';
    
// get all schools

export const GET_SCHOOLS_START = 'GET_SCHOOLS_START';
export const GET_SCHOOLS_SUCCESS = 'GET_SCHOOLS_SUCCESS';
export const GET_SCHOOLS_ERROR = 'GET_SCHOOLS_ERROR';

// get single school
export const GET_SCHOOL_START = 'GET_SCHOOL_START';
export const GET_SCHOOL_SUCCESS = 'GET_SCHOOL_SUCCESS';
export const GET_SCHOOL_ERROR = 'GET_SCHOOL_ERROR';

// Update a school
export const UPDATE_SCHOOL_SUCCESS = 'UPDATE_SCHOOL_SUCCESS';
export const UPDATE_SCHOOL_FAILURE = 'UPDATE_SCHOOL_FAILURE';
export const UPDATE_SCHOOL_START = 'UPDATE_SCHOOL_START';

// Delete a school
export const DELETE_SCHOOL_SUCCESS = 'DELETE_SCHOOL_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';
export const DELETE_SCHOOL_START = 'DELETE_SCHOOL_START';

// Class action types

export const ADD_CLASS_START = 'ADD_CLASS_START';
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS';
export const ADD_CLASS_ERROR = 'ADD_CLASS_ERROR';

export const GET_CLASSES_START = 'GET_CLASSES_START';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const UPDATE_CLASS_FAILURE = 'UPDATE_CLASS_FAILURE';
export const UPDATE_CLASS_START = 'UPDATE_CLASS_START';


// Student

export const ADD_STUDENT_START = 'ADD_STUDENT_START';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_ERROR = 'ADD_STUDENT_ERROR';

export const GET_STUDENTS_START = 'GET_STUDENTS_START';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_ERROR = 'GET_STUDENTS_ERROR';

export const ONCHANGE_SCHOOL_SUCCESS = 'ONCHANGE_SCHOOL_SUCCESS';
